baseurl = "courses/ant6937-s2019/"
languageCode = "en-uS"
defaultContentLanguage = "en-us"
title = "ANT 6937, Spring 2019"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Fernando Campos"
  bio = ""
  job = "Assistant Professor"
  location = "UTSA"
  gravatarEmail = "fernando.campos@utsa.edu"
  # Your profile picture
#  picture = ""
  twitter = "F_A_Campos"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class='sidebar-button-icon fa fa-lg fa-home'></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "modules"
  name = "Modules"
  pre = "<i class='material-icons'>dashboard</i>"
  url = "/modules"
[[menu.main]]
  weight = 3
  identifier = "cheatsheets"
  name = "Cheat Sheets"
  pre = "<i class='material-icons'>build</i>"
  url = "/cheatsheets"
[[menu.main]]
  weight = 4
  identifier = "syllabus"
  name = "Syllabus"
  pre = "<i class='material-icons'>date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 5
  identifier = "policies"
  name = "Policies"
  pre = "<i class='material-icons'>gavel</i>"
  url = "/policies"


[[menu.footer]]
  weight = 2
  identifier = "GitHub"
  name = "Github"
  pre = "<i class='fab fa-github fa-2x'></i>"
  url = "https://github.com/camposfa/ant-6937-spring-2019"
[[menu.footer]]
  weight = 3
  name = "DataCamp"
  pre = "<i class='material-icons'>video_library</i>"
  url = "https://www.datacamp.com/groups/ant-6973-data-visualization-and-exploration"
[[menu.footer]]
  weight = 4
  name = "Textbook: R4DS"
  pre = "<i class='material-icons'>book</i>"
  url = "http://r4ds.had.co.nz/"
[[menu.footer]]
  weight = 5
  name = "Textbook: Wilke"
  pre = "<i class='material-icons'>book</i>"
  url = "https://serialmentor.com/dataviz/"
[[menu.footer]]
  weight = 6
  name = "Textbook: Healy"
  pre = "<i class='material-icons'>book</i>"
  url = "https://socviz.co/"



[[menu.sidebar]]
  weight = 1
  pre = "<i class='material-icons'>timeline</i>"
  name = "Climate Change"
  url = "#climate"
[[menu.sidebar]]
  weight = 2
  pre = "<i class='material-icons'>directions_boat</i>"
  name = "Overfishing"
  url = "#fish"
[[menu.sidebar]]
  weight = 3
  pre = " <i class='material-icons'>bug_report</i>"
  name = "Ecological Simulation"
  url = "#popdyn"
[[menu.sidebar]]
  weight = 4
  pre = " <i class='material-icons'>my_location</i>"
  name = "Geospatial"
  url = "#spatial"
 [[menu.sidebar]]
weight = 5
  pre = " <i class='material-icons'>trending_down</i>"
  name = "Mass Extinctions"
  url = "#extinction"



[[menu.tools]]
  weight = 1
  name = "GitHub"
  url = "#github"
  pre = "<i class='fab fa-github'></i>"
[[menu.tools]]
  weight = 3
  name = "Travis-CI"
  url = "#travis"
  pre = "<i class='material-icons'>check_circle</i>"
[[menu.tools]]
  weight = 2
  name = "RMarkdown"
  url = "#rmarkdown"
  pre = "<br/><img src='/img/rmarkdown2.png' alt='rmarkdown' height='36'><br/>"
[[menu.tools]]
  weight = 4
  name = "R Packages"
  url = "#packages"
  pre = "<i class='fa fa-archive'></i>"
[[menu.tools]]
  weight = 5
  name = "Docker"
  url = "#docker"
  pre = "<i class='fa fa-docker'></i>"
[[menu.tools]]
  weight = 6
  name = "Cloud"
  url = "#cloud"
  pre = "<i class='fa fa-cloud'></i>"  
[[menu.tools]]
  weight = 7
  name = "Web design"
  url = "#website"
  pre = "<i class='material-icons'>language</i>"
[[menu.tools]]
  weight = 8
  name = "Shiny"
  url = "#shiny"
  pre = "<br/><img src='/img/shiny.png' alt='shiny' height='36'><br/>"

[params]
  dateFormat = "January 2, 2006"
  background = "/img/mugesketch.png"
  math = "true"
  favicon = "/img/baboon.png"
