baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "ANT 6973, Spring 2021"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Fernando Campos"
  bio = ""
  job = "Assistant Professor"
  location = "UTSA"
  gravatarEmail = "fernando.campos@utsa.edu"
  # Your profile picture
#  picture = ""
  twitter = "F_A_Campos"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class='sidebar-button-icon fa fa-lg fa-home'></i>"
  url = "/"
#[[menu.main]]
#  weight = 3
#  identifier = "cheatsheets"
#  name = "Cheat Sheets"
#  pre = "<i class='material-icons'>build</i>"
#  url = "/cheatsheets"
[[menu.main]]
  weight = 4
  identifier = "schedule"
  name = "Schedule"
  pre = "<i class='material-icons'>date_range</i>"
  url = "/schedule"
[[menu.main]]
  weight = 5
  identifier = "policies"
  name = "Policies"
  pre = "<i class='material-icons'>gavel</i>"
  url = "/policies"


[[menu.footer]]
  weight = 2
  identifier = "GitHub"
  name = "Github"
  pre = "<i class='fab fa-github fa-2x'></i>"
  url = "https://github.com/camposfa/data-viz-course"
[[menu.footer]]
  weight = 3
  name = "Textbook: Wilke"
  pre = "<i class='material-icons'>book</i>"
  url = "https://clauswilke.com/dataviz/"
[[menu.footer]]
  weight = 4
  name = "Textbook: Healy"
  pre = "<i class='material-icons'>book</i>"
  url = "https://socviz.co/"
[[menu.footer]]
  weight = 5
  name = "Textbook: ModernDive"
  pre = "<i class='material-icons'>book</i>"
  url = "https://moderndive.com"
[[menu.footer]]
  weight = 6
  name = "Textbook: R4DS"
  pre = "<i class='material-icons'>book</i>"
  url = "http://r4ds.had.co.nz/"


[[menu.tools]]
  weight = 1
  name = "R Studio"
  url = "#rstudio"
  pre = "<br/><img src='/img/logos/RStudio-Ball.png' alt='rstudio' height='36'><br/>"
[[menu.tools]]
  weight = 2
  name = "Data Visualization"
  url = "#ggplot2"
  pre = "<br/><img src='/img/logos/hex-ggplot2.png' alt='ggplot2' height='36'><br/>"
[[menu.tools]]
  weight = 3
  name = "Data Transformation"
  url = "#dplyr"
  pre = "<br/><img src='/img/logos/hex-dplyr.png' alt='dplyr' height='36'><br/>"
[[menu.tools]]
  weight = 4
  name = "Data Import"
  url = "#readr"
  pre = "<br/><img src='/img/logos/hex-readr.png' alt='readr' height='36'><br/>"
[[menu.tools]]
  weight = 5
  name = "R Markdown"
  url = "#rmarkdown"
  pre = "<br/><img src='/img/logos/rmarkdown.png' alt='rmarkdown' height='36'><br/>"


[params]
  dateFormat = "January 2, 2006"
  background = "/img/mugesketch.png"
  math = "true"
  favicon = "/img/baboon.png"
