---
title: "Introduction and Setup"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Complete in Class

To start becoming familiar with R, we're going to complete some interactive, self-paced lessons using [swirl](https://swirlstats.com/).

<br>

**Steps:**

<br>

1. Open up RStudio, type the following in the console pane (next to the `>` symbol), and press Enter. This should install the 'swirl' package for R. That means the package files have been downloaded and saved to your computer. 

```
install.packages("swirl")
```

<br>

2. But to actually use the functions in the swirl package, we need to **load** the package into our current R session. We do this using the `library()` function, providing it the name of the package that we want to load.

```
library("swirl")
```

<br>

3. Enter the following command to install a very basic course called "R_Programming_E" (admittedly, not the greatest name).

```
install_course_github("swirldev", "R_Programming_E")
```

<br>

4. Okay! We're ready to run the course. Enter the following:

```
swirl()
```

<br>

5. When prompted (after a few screens), choose the lesson called "**Basic Building Blocks**".

<hr>

## Complete over the next week or two

In the same `swirl` course called "R_Programming_E", complete the following lessons:

- 2: Workspace and Files
- 3: Sequences of Numbers
- 4: Vectors
- 5: Missing values
- 8: Logic
- 9: Functions
- 12: Looking at Data

<br>

**Note:** these exercises will not be graded, and I can't even check if you've completed them or not. _So don't get stressed if you find them challenging._ They are meant to teach basic skills in R that will be very useful going forward.

To complete these courses, there's no need to reinstall `swirl`. Just type `swirl()` at the console (step 4), and you'll get back to the list of available lessons.

<br><br>

**Tip:** here are some commands that you can use while working on a `swirl` lesson.

```
| When you are at the R prompt (>):
| -- Typing skip() allows you to skip the current question.
| -- Typing bye() causes swirl to exit. Your progress will be saved.
| -- Typing main() returns you to swirl's main menu.
| -- Typing info() displays these options again.
```